---
title: "adaptivefMRI"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

Read fMRI data, for example using oro.nifti:
```{r readdata, cache=TRUE, echo=TRUE, collapse=TRUE}
library(BayGMRF)
library(oro.nifti)
library(parallel)
data <- readNIfTI(system.file("filtered_func_data.nii",package = "BayGMRF"))
```

Produce a mask: Ignore voxels where signal is zero:
```{r mask, cache=TRUE, echo=TRUE, collapse=TRUE}
mask <- apply(data,1:3,sum)!=0
image(as.nifti(mask))
```

```{r prepare, cache=TRUE, echo=TRUE, collapse=TRUE}
new<-prepare.regular(data[,,11,],mask[,,11])
```

## Stimuli
* Visueller Stimulus: 30s on/off
* auditiver Stimulus: 45s on/off
```{r stimuli, cache=TRUE, echo=TRUE, collapse=TRUE}
visual <- rep(c(-0.5,0.5), each=30, times=9) # 9 = 540/(30*2)
auditory <- rep(c(-0.5,0.5), each=45, times=6)  # 6 = 540/(45*2)
```

## plotten
```{r plotstimuli, cache=TRUE, echo=TRUE, collapse=TRUE}
time <- 1:540
par(mfrow=c(1,2))
plot(time, visual, type="l", xlab="Zeit [sec]", ylab="Visueller Stimulus")
plot(time, auditory, type="l", xlab="Zeit [sec]", ylab="Auditiver Stimulus")
```


## Hemodynamic Response Function (HRF)
```{r hrf, cache=TRUE, echo=TRUE, collapse=TRUE}
hrf <- c(dgamma(1:15, 4, scale=1.5), rep(0, length(visual)-15)) 
plot(hrf[1:30], type="l", xlab = "Zeit [sec]")
visual.hrf <- convolve(hrf, visual)
auditory.hrf <- convolve(hrf, auditory)
```

# Aufnahmen nur alle drei Sekunden
```{r cache=TRUE, echo=TRUE, collapse=TRUE}
index <- seq(3, 540, by=3)
visual.hrf <- visual.hrf[index] 
auditory.hrf <- auditory.hrf[index] 
plot(index, visual.hrf, type="l", xlab="Zeit [sec]", ylab="Visueller Stimulus")
lines(index, auditory.hrf, type="l", xlab="Zeit [sec]", ylab="Auditiver Stimulus",col="blue")
```

## Now prepare for BayMGRF

```{r single, cache=TRUE, echo=TRUE, collapse=TRUE}
X <- auditory.hrf
Y <- new$data
hyper<-list("sigma2.a"=100,"sigma2.b"=100,"tau.a"=0.001,"tau.b"=1)
mcmc<-list("iterations"=600,"thin"=1,"burnin"=100)
options=list("tau"=TRUE,"sigma2"=TRUE,"print.time"=FALSE,"X.true"=FALSE)
test <- BayGMRF(Y,X=X,Q.list=list(new$nn),mcmc=mcmc,options=options,hyper=hyper)
```

```{r singleresults, cache=TRUE, echo=TRUE, collapse=TRUE}
beta.med<-apply(test$beta[[1]],2,median)
img.reg.mask(beta.med,new$coords,dim(data)[1:2])
par(mfrow=c(2,1))
plot(test$tau)
plot(test$sigma2)
```

```{r double, cache=TRUE, echo=TRUE, collapse=TRUE}
X2 <- list("auditory"=auditory.hrf,"visual"=visual.hrf)
Q.list <- list(new$nn)
Q.X=c(1,1)
hyper2<-list("sigma2.a"=1,"sigma2.b"=1,"tau.a"=rep(0.001,2),"tau.b"=rep(1,2))
options2=list("tau"=rep(TRUE,2),"sigma2"=TRUE,"print.time"=TRUE,"X.true"=rep(FALSE,2))
test1 <- BayGMRF(Y,X=X2,Q.list=Q.list,mcmc=mcmc,options=options2,hyper=hyper2,Q.X=Q.X)
test2 <- BayGMRF(Y,X=X2,Q.list=Q.list,mcmc=mcmc,options=options2,hyper=hyper2,Q.X=Q.X)
test3 <- BayGMRF(Y,X=X2,Q.list=Q.list,mcmc=mcmc,options=options2,hyper=hyper2,Q.X=Q.X)
test4 <- BayGMRF(Y,X=X2,Q.list=Q.list,mcmc=mcmc,options=options2,hyper=hyper2,Q.X=Q.X)
```

```{r}
library(coda)
tau1.sample<-as.mcmc.list(list(mcmc(test1$tau[,1]),mcmc(test2$tau[,1]),mcmc(test3$tau[,1]),mcmc(test4$tau[,1])))
tau2.sample<-as.mcmc.list(list(mcmc(test1$tau[,2]),mcmc(test2$tau[,2]),mcmc(test3$tau[,2]),mcmc(test4$tau[,2])))
coda::gelman.diag(tau1.sample)
coda::gelman.diag(tau2.sample)

sigma2.sample<-as.mcmc.list(list(mcmc(test1$sigma2),mcmc(test2$sigma2),mcmc(test3$sigma2),mcmc(test4$sigma2)))
coda::gelman.diag(sigma2.sample)
```
```{r}
for (i in 1:2)
  for (j in 1:1390)
  {
    sample<-as.mcmc.list(list(mcmc(test1$beta[[i]][,j]),mcmc(test2$beta[[i]][,j]),mcmc(test3$beta[[i]][,j]),mcmc(test4$beta[[i]][,j])))
    temp<-coda::gelman.diag(sample)
    if (temp$psrf[2]>1.1)print(paste(i,j))
  }
```


```{r doubleresults, cache=TRUE, echo=TRUE, collapse=TRUE}
par(mfrow=c(2,1))
beta.med1<-apply(test2$beta[[1]],2,median)
img.reg.mask(beta.med1,new$coords,dim(data)[1:2])
beta.med2<-apply(test2$beta[[2]],2,median)
img.reg.mask(beta.med2,new$coords,dim(data)[1:2])
par(mfrow=c(2,2))
plot(test2$tau[,1])
plot(test2$tau[,2])
plot(test2$sigma2)
```

```{r multipleprepare, cache=TRUE, echo=TRUE, collapse=TRUE}
Q.list3<-mclapply(1:dim(data)[3],function(i,data,mask)
{return(prepare.regular(data[,,i,],mask[,,i])$nn)},data,mask)
Y.list<-mclapply(1:dim(data)[3],function(i,data,mask)
{return(prepare.regular(data[,,i,],mask[,,i])$data)},data,mask)
Y.list<-mclapply(Y.list,function(Y)t(Y))
Y.l<-unlist(mclapply(Y.list,dim))
Y.l<-Y.l[seq(2,42,by=2)]
partial<-mclapply(c(1:length(Y.l),1:length(Y.l)),function(i,Yl)
{
  if (i==1){a=1}else{a<-sum(Yl[1:(i-1)])+1}
  b<-sum(Yl[1:i])
  return(a:b)
},Y.l)
Y3<-t(matrix(unlist(Y.list),nrow=180))
Q.X3<-rep(1:2,each=21)
X3<-mclapply(Q.X3,function(i,a,v)ifelse(i==1,return(a),return(v)),a=auditory.hrf,v=visual.hrf)
options2$share.tau<-Q.X3
options2$partial=partial
options2$X.true=rep(FALSE,42)
options2$print.time<-TRUE
test3 <- BayGMRF(Y=Y3,X=X3,Q.list=Q.list3,mcmc=mcmc,options=options2,hyper=hyper2,Q.X=rep(1:21,2))
```

```{r multipleresults, cache=TRUE, echo=TRUE, collapse=TRUE}
coords.list<-mclapply(1:dim(data)[3],function(i,data,mask)
{return(prepare.regular(data[,,i,],mask[,,i])$coords)},data,mask)
beta1<-mclapply(1:21,function(i,test3,beta)apply(test3$beta[[i]],2,median),test3,beta)
beta1<-make.3D.from.coords(beta1,coords.list,c(64,64))
beta2<-mclapply(22:42,function(i,test3,beta)apply(test3$beta[[i]],2,median),test3,beta)
beta2<-make.3D.from.coords(beta2,coords.list,c(64,64))
image(beta1)
image(beta2)
par(mfrow=c(2,2))
plot(test3$tau[,1])
plot(test3$tau[,2])
plot(test3$sigma2)
```

## 3D

```{r}
pp<-prepare.regular(data,mask)
options4=list("tau"=rep(TRUE,2),"sigma2"=TRUE,"print.time"=TRUE,"X.true"=rep(FALSE,2))
test4 <- BayGMRF(Y=pp$data,X=X2,Q.list=list(pp$nn),mcmc=mcmc,options=options2,hyper=hyper2,Q.X=c(1,1))

```

```{r}
beta.med1<-apply(test4$beta[[1]],2,median)
beta.med2<-apply(test4$beta[[2]],2,median)

beta.med<-beta.med1
m<-array(NA,c(dim(data)[1:3]))
for (i in 1:dim(pp$coords)[1])
  {
    m[pp$coords[i,1],pp$coords[i,2],pp$coords[i,3]]<-beta.med[i]
}
beta1<-oro.nifti::as.nifti(m)
beta.med<-beta.med2
m<-array(NA,c(dim(data)[1:3]))
for (i in 1:dim(pp$coords)[1])
  {
    m[pp$coords[i,1],pp$coords[i,2],pp$coords[i,3]]<-beta.med[i]
}
beta2<-oro.nifti::as.nifti(m)
  
image(beta1)
image(beta2)
```

